Initial Commit.
eclipse-kanto/aws-connector pull request #1
Opened 2023-09-12 07:14 UTC by yonko-gospodinov

2023-09-20 12:01 UTC, k-gostev requested changes
@yonko-gospodinov Thank you for this contribution!

I have tested it a bit and seems that it is working fine. The code follows the structure and the semantics of the other connectors so no comments there. There are couple of nits that I found, but besides that seems fine to me for an initial contribution.

2023-09-20 12:01 UTC, k-gostev commented on go.mod
> +	github.com/imdario/mergo v0.3.12
github.com/imdario/mergo v1.0.0 was released a couple of months ago.  We should see if the update is easy to be done in this PR. If there are some backward incompatible changes that needs more effort we will do this in another task.

2023-09-20 12:01 UTC, k-gostev commented on cmd/aws-connector/app/launch.go
> +import (
Imports should be organised in all go files as follows:
import(
\<go standard libraries\>

\<project libraries github.com/eclipse-kanto/aws-connector/*\>

\<others\>
)
ref: https://github.com/golang/go/wiki/CodeReviewComments#imports

2023-09-20 12:01 UTC, k-gostev commented on cmd/aws-connector/main.go
> +	if err := mergo.Map(settings, cli, mergo.WithOverwriteWithEmptyValue); err != nil {
nit
```suggestion
	if err := mergo.Map(settings, suiteFlags.Copy(f), mergo.WithOverwriteWithEmptyValue); err != nil {
```

2023-09-20 12:01 UTC, k-gostev commented on config/settings.go
> +	"io/ioutil"
`io/util` is deprecated as of go 1.16 and should be replaced with `os`

2023-09-20 12:01 UTC, k-gostev commented on routing/bus/internal/testing/utils.go
> +func AssertRouterHandler(t *testing.T, expectedHandlerName, expectedSubcribeTopic, expectedPublishTopic string, refHandler reflect.Value) {
typo
```suggestion
func AssertRouterHandler(t *testing.T, expectedHandlerName, expectedSubscribeTopic, expectedPublishTopic string, refHandler reflect.Value) {
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler.go
> +		// Convert incomming message to shadow messages (if needed)
```suggestion
		// Convert incoming message to shadow messages (if needed)
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler.go
> +// HandleMessage creates a new message with the same payload as the incoming message and sets the correct topic so that the message can be forwarded to AWS Iot Hub
```suggestion
// HandleMessage creates a new message with the same payload as the incoming message and sets the correct topic so that the message can be forwarded to AWS IoT Hub
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler.go
> +// toShadowTopic convert Ditto topic to its coresponding device shadow topic and if its an update message.
```suggestion
// toShadowTopic convert Ditto topic to its corresponding device shadow topic and if its an update message.
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler.go
> +		// Prepare update messages for found atributes.
```suggestion
		// Prepare update messages for found attributes.
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler.go
> +			messages = append(messages, message)
looks like there is no need to assign new variable here. Same for the feature search below
```suggestion
			messages = append(messages, h.toShadowMessage(env, "", attributes))
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler_test.go
> +	// 4. Assert deletion of feture definition (root thing).
```suggestion
	// 4. Assert deletion of feature definition (root thing).
```

2023-09-20 12:01 UTC, k-gostev commented on routing/message/handlers/passthrough/device_handler_test.go
> +	// 6. Assert deletion of feture definition (child thing).
```suggestion
	// 6. Assert deletion of feature definition (child thing).
```

2023-09-21 10:03 UTC, k-gostev commented on go.mod
> +	github.com/imdario/mergo v0.3.12
this needs to be fixed in the `suite-connector` first

2023-09-25 09:11 UTC, dimitar-dimitrow requested changes

2023-09-25 09:11 UTC, dimitar-dimitrow commented on config/settings.go
> +	PayloadFiltersRegexp []*regexp.Regexp
Add `json:"-"` for the regular expressions fields to exclude them from the JSON.

2023-09-25 09:11 UTC, dimitar-dimitrow commented on config/settings_test.go
> +	err := os.WriteFile(path, []byte(content), os.ModePerm)
Use [ioutil.TempFile](https://golang.org/pkg/io/ioutil/#TempFile) with empty _dir_ argument to create the file within the default temporary directory.

2023-09-25 09:11 UTC, dimitar-dimitrow commented on cmd/aws-connector/main.go
> +	if err := settings.ReadDeviceID(); err != nil {
I think that it is a good idea the default MQTT _clientId_ to be equal to the _deviceId_(CN, ThingName). This will enable [life cycle events](https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html) and the usage of [thing policy variables](https://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-variables.html).

2023-09-27 07:58 UTC, dimitar-dimitrow requested changes

2023-09-27 07:58 UTC, dimitar-dimitrow commented on NOTICE.md
> +golang/go (1.19.4)
The go version should be aligned with the go version used for the Kanto releases. Currently it is [1.21.0](https://github.com/eclipse-kanto/kanto/blob/main/.github/workflows/release.yaml#L89).

2023-09-27 07:58 UTC, dimitar-dimitrow commented on routing/message/handlers/passthrough/device_handler.go
> +	topicUpdate = "update"
Update performs a merge in the shadow document. When a container is deleted, the container management SoftwareUpdatable feature send Ditto installedDependencies property modify with the deleted container missing. As in the AWS shadows a merge is performed the deleted container persist in the installedDependency part of the shadow document. Eventually this leads to over the limit shadow document:
```
{
    "timestamp": "2023-09-25 13:15:20.495",
    "logLevel": "ERROR",
    "traceId": "8549dcc6-87b6-a5db-75ab-f442872a02fa",
    "accountId": "797412740850",
    "status": "Failure",
    "eventType": "UpdateThingShadow",
    "protocol": "MQTT",
    "deviceShadowName": "edge:SF3-C-0006W",
    "topicName": "$aws/things/edge:SF3-C-0006W/shadow/name/edge:containers:SoftwareUpdatable/update",
    "details": "Json document too large.  Size is 8359, max allowed: 8192"
}
```
Unfortunately I could not see an easy solution to this problem.

2023-09-27 13:24 UTC, yonko-gospodinov commented on routing/message/handlers/passthrough/device_handler.go
> +	topicUpdate = "update"
Unfortunately AWS Shadows support only 'merge', while Ditto has 'modify' as preferred command. The asynchronous AWS MQTT Broker makes the 'modify' operation expensive and hard to implement. To do so, you need to send 'delete' + 'merge' and both messages must be synchronized either on the cloud (via custom synchronous queue) or on the edge (via 'delete' response).

2023-09-27 14:24 UTC, hristobojilov approved these changes

2023-09-27 14:37 UTC, dimitar-dimitrow commented on routing/message/handlers/passthrough/device_handler.go
> +	topicUpdate = "update"
We discussed some potential solutions of the problem. @yonko-gospodinov will investigate, whether it is possible to synchronization the 'delete' + 'merge' messages on the edge side via 'delete' response with the current suite-connector API. I will check whether this problem impacts only SoftwareUpdatable features and how much is the effort to switch to Ditto merge messages for the impacted features.

The further progress will be traced in a separate issue - #3.

2023-09-27 14:37 UTC, dimitar-dimitrow approved these changes

2023-09-28 06:24 UTC, k-gostev approved these changes
Thank you all for the contribution and collaboration! 
Waiting for https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10601 to confirm the IP checks and we are good to go.

2023-10-05 07:02 UTC, merged